name: HowAwayAreYou
attributes:
  ORGANIZATIONNAME: Crazism
options:
  bundleIdPrefix: net.crazism
settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: KC8N9BMQJY
targets:
  HowAwayAreYou:
    platform: iOS
    deploymentTarget: "13.0"
    type: application
    sources: HowAwayAreYou
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: net.crazism.HAAY
      MARKETING_VERSION: 1.0.0
      TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - sdk: AVFoundation.framework
    preBuildScripts:
      - name: SwiftLint
        script: |
          if mint list | grep -q 'SwiftLint'; then
            mint run swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  HowAwayAreYouTests:
    platform: iOS
    deploymentTarget: "13.0"
    type: bundle.unit-test
    sources: HowAwayAreYouTests
    dependencies:
      - target: HowAwayAreYou
  HowAwayAreYouUITests:
    platform: iOS
    deploymentTarget: "13.0"
    type: bundle.ui-testing
    sources: HowAwayAreYouUITests
    dependencies:
      - target: HowAwayAreYou
schemes:
  HowAwayAreYou:
    templates:
      - BaseScheme
schemeTemplates:
  BaseScheme:
    build:
      targets:
        HowAwayAreYou: all
        HowAwayAreYouTests: [test]
        HowAwayAreYouUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets: [HowAwayAreYouTests, HowAwayAreYouUITests]
      gatherCoverageData: true
      coverageTargets: [HowAwayAreYou]
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
